### ISSUE TITLE
Alert message in action bar doesn't appear

### ISSUE THREAD

**Issue by Noraksing** [ItsLewizzz/InventoryFullPlus#4]
The alert message: "&cYour Inventory Is Full!" doesn't appear in the action bar like it's supposed to, even when it's enabled in the config file. Reloading the plugin doesn't help. Chat message and title works but, for some reason, this one doesn't.

**Comment by RedstoneFuture** [comment]
I can replicate it.

**Comment by RedstoneFuture** [comment]
https://pastebin.com/aGDb56He

tested on PaperMC 1.16.5 #443
InventoryFullPlus 2.5.9

**Comment by ItsLewizzz** [comment]
Fixed in v3.0.0.
