### ISSUE TITLE
[Request] New Hologram Plugin Support - Decent Holograms

### ISSUE THREAD

**Issue by iCaitlyn** [ItsLewizzz/InventoryFullPlus#6]
Hi,

Is it possible for support of [Decent Holograms](https://www.spigotmc.org/resources/decent-holograms-1-8-1-18-papi-support-no-dependencies.96927/) to be added in the future?
Their known API documentation is located at [their Docs](https://wiki.decentholograms.eu/api/get-started).

**Comment by ItsLewizzz** [comment]
I’ll have a look into it, thanks.

**Comment by ItsLewizzz** [comment]
Added in v3.1.0
